name: ProductOfArrayExceptSelf
description: |
  Given an integer array `nums`, return an array `output` where `output[i]` is the product of all the elements of `nums`
  except `nums[i]`.
  
  Each product is guaranteed to fit in a 32-bit integer.
  
  Follow-up: Could you solve it in O(n) time without using the division operation?
difficulty: Easy
tags:
  - arrays
  - hashing
template:
  name: SingleFunction
  args:
    input:
      - name: nums
        type: int[]
    output: int
